-- =========================================================
-- Donation App - PostgreSQL Schema
-- Java 21 / Spring Boot 3.5.4 / PostgreSQL
-- =========================================================

-- Optional
CREATE SCHEMA IF NOT EXISTS public;

-- =========================================================
-- Table: donation_cause
-- =========================================================
CREATE TABLE IF NOT EXISTS donation_cause (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    display_order INTEGER,
    allow_custom_amount BOOLEAN NOT NULL DEFAULT TRUE,
    min_amount NUMERIC(12,2),
    max_amount NUMERIC(12,2),
    currency_code VARCHAR(3) NOT NULL,
    active_from TIMESTAMP WITH TIME ZONE,
    active_to TIMESTAMP WITH TIME ZONE,
    image_url VARCHAR(500),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),

    CONSTRAINT uk_donation_cause_code UNIQUE (code),
    CONSTRAINT chk_donation_cause_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_donation_cause_amount_range
        CHECK (
            min_amount IS NULL
            OR max_amount IS NULL
            OR max_amount >= min_amount
        )
);

-- =========================================================
-- Table: donation_cause_i18n
-- =========================================================
CREATE TABLE IF NOT EXISTS donation_cause_i18n (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cause_id BIGINT NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    title VARCHAR(255) NOT NULL,
    short_description VARCHAR(1000),
    full_description TEXT,
    cta_label VARCHAR(100),
    thank_you_message TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),

    CONSTRAINT fk_donation_cause_i18n_cause
        FOREIGN KEY (cause_id) REFERENCES donation_cause(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_donation_cause_i18n_cause_lang
        UNIQUE (cause_id, language_code)
);

-- =========================================================
-- Table: donation_transaction
-- =========================================================
CREATE TABLE IF NOT EXISTS donation_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref VARCHAR(50) NOT NULL,
    cause_id BIGINT NOT NULL,
    donor_user_id VARCHAR(100) NOT NULL,
    donor_display_name VARCHAR(255),
    donor_email VARCHAR(255),
    amount NUMERIC(12,2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payment_status VARCHAR(50),
    payment_reference VARCHAR(100),
    external_reference VARCHAR(100),
    message_to_organization VARCHAR(1000),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),

    CONSTRAINT uk_donation_transaction_ref UNIQUE (transaction_ref),

    CONSTRAINT fk_donation_transaction_cause
        FOREIGN KEY (cause_id) REFERENCES donation_cause(id),

    CONSTRAINT chk_donation_transaction_status
        CHECK (status IN ('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')),

    CONSTRAINT chk_donation_transaction_amount
        CHECK (amount > 0)
);

-- =========================================================
-- Indexes
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_donation_cause_status
    ON donation_cause(status);

CREATE INDEX IF NOT EXISTS idx_donation_cause_display_order
    ON donation_cause(display_order);

CREATE INDEX IF NOT EXISTS idx_donation_cause_i18n_cause_id
    ON donation_cause_i18n(cause_id);

CREATE INDEX IF NOT EXISTS idx_donation_cause_i18n_language_code
    ON donation_cause_i18n(language_code);

CREATE INDEX IF NOT EXISTS idx_donation_transaction_cause_id
    ON donation_transaction(cause_id);

CREATE INDEX IF NOT EXISTS idx_donation_transaction_donor_user_id
    ON donation_transaction(donor_user_id);

CREATE INDEX IF NOT EXISTS idx_donation_transaction_created_at
    ON donation_transaction(created_at);

CREATE INDEX IF NOT EXISTS idx_donation_transaction_status
    ON donation_transaction(status);